// Code generated by go generate; DO NOT EDIT.
// This file was generated by genconstants.go

package main

import "fmt"

var (
	buildDate    = "2022-December-3"
	buildTag     = "ade54a4abe308c6e8a0a4ea605b684ab6546a6f2"
	buildVersion = "0"
)

func printBuildInfo() {
	fmt.Println("Build version: 0")
	fmt.Println("Build date: 2022-December-3")
	fmt.Println("Build tag: ade54a4abe308c6e8a0a4ea605b684ab6546a6f2")
}
